### ISSUE TITLE
Return or use provided requestId in sendWithData

### ISSUE THREAD

**Issue by nagyv** [MikalDev/ConstructAddons#1]
**Is your feature request related to a problem? Please describe.**
I would like to know exactly the response on a given message sent. For this it would be great to build a dictionary with the requestId-s and their corresponding callbacks to be used to work with the received message.

**Describe the solution you'd like**
The best would be if sendWithData could return the requestId used. As sendWithData is an action, it does not support the returnType (AFAIK).

**Describe alternatives you've considered**
Another possibility would be to either store the last requestId, and get it with an expression. This could lead to problems though, if there are several concurrent requests, and a newer request overwrites the stored request.
Another possibility would be to provide the requestId to sendWithData. In this case sendWithData would use its current requestId logic only if no ID was provided.

**Comment by MikalDev** [comment]
Thanks for the feedback, I will take a look at this. I will look at the original C2 runtime plugin and see how they handle it.

**Comment by MikalDev** [comment]
I checked the original official gamesparks c2 plugin and they also do not pass back a tag or ID with the last data. However, they did add a lot more triggers, one for each particular request. I think it will be pretty easy to add that (a parameter to the the response trigger for event type ) and also create at least a dictionary with a per event type lastResponseData, so you can ask for the particular event type last response. Which is better than the official plugin, in my understanding. So, at least different events won’t collide with lastData, but it will require serializing request of the same type. Is that useful for you, if that’s implemented?

Here’s the other repo:
https://bitbucket.org/gamesparks/gamesparks-construct2/src/60a66961fa6713a6f867cbf3505e0f413fea96e6/gamesparks/runtime.js?at=master&fileviewer=file-view-default

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nagyv** [comment]
Hi,

my recommendation would be to make `requestId` optionally provided by the
user. Just wrap `json.requestId = (new Date()).getTime() + "_" +
(++this.requestCounter);` in an if statement, like

```
if (!json.requestId) {
  json.requestId = (new Date()).getTime() + "_" + (++this.requestCounter);
}
```

This is a really flexible and 100% backward-compatible solution. ;)

MikalDev <notifications@github.com> ezt írta (időpont: 2019. febr. 17., V,
7:06):

**Comment by MikalDev** [comment]
I pushed up a new version which added an action to sendData with request ID.
Also update gamesparks.js ('official SDK') to allow for user request ID and also change the same file to _not_ delete requestID from the response (probably something to be aware, they must be deleting it for a reason?) Try it out... (I included the addon in the repo too (will update construct addon site after feedback.) Thanks for the comments and suggestions.

**Comment by nagyv** [comment]
Thanks, I've checked it. Putting it to test will need more time, but the code looks ok for me.

**Comment by MikalDev** [comment]
Closing issue with new functionality added.
