### ISSUE TITLE
[GameSparksMinimal] GameSparks is undefined in exported projects

### ISSUE THREAD

**Issue by nagyv** [MikalDev/ConstructAddons#2]
**Describe the bug**

Due to https://github.com/Scirra/Construct-3-bugs/issues/2621 the current gamesparksminimal plugin does not work in exported projects. 

I've tried to for your repo, and work around the bug in c3ide, but could not figure out how to do it in c3ide. Anyway, you can find a working version of the plugin at https://www.dropbox.com/s/y1brhykvs6ob5h5/gamesparksminimal.c3addon?dl=0

**To Reproduce**

See https://github.com/Scirra/Construct-3-bugs/issues/2621

**Expected behavior**
Exported project works fine.

**Additional context**
It's really hard to contribute to your addons if you use c3ide. :(
Thanks for your work!

**Comment by MikalDev** [comment]
Will look at this. The designer of c3IDE is updating the file format so that it will be easier to use with source control. It will still require use of c3IDE, but there will be separate files for source control. Thanks for the report.

**Comment by MikalDev** [comment]
Changed file dependencies to inline script. Exported project with nw.exe on Windows 10 worked in my environment. Please test.

**Comment by nagyv** [comment]
html5 export works too

thanks

**Comment by MikalDev** [comment]
Closing with confirmation of html5 export working also. Also noting that the bug in C3 was also fixed, so could revert to the external script if needed.
